### ISSUE TITLE
Hi! Are there any plans to update the library for vue 3?

### ISSUE THREAD

**Issue by Denisfront** [CyberAP/vue-component-media-queries#12]
![telegram-cloud-photo-size-2-5210709909430188042-y](https://user-images.githubusercontent.com/56231349/153804545-59d26a76-4d2b-4082-9166-de65705bafc8.jpg)

**Comment by CyberAP** [comment]
@Denisfront hi!

There are no plans to update this library for Vue 3 at the moment. I believe your best course of action would be to use Media Query composables ([example](https://vueuse.org/core/usemediaquery/)), since they have a much nicer API than components with scoped slots. Though it might take some time to find one that supports SSR out of the box.

If you're migrating existing code from Vue 2 you can use [Vue Migration Mode](https://v3-migration.vuejs.org/migration-build.html), the library itself should be working fine in the compatibility mode.

If there's enough demand for a proper Vue 3 version of this library I might reconsider it at some time (please comment here if you need it), but for now I am closing this. Thanks for bringing attention to it!
